'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
const root=path.resolve(__dirname,'..'),file=path.join(root,'src/core/deferredFormAttachment.ts');
const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{fileName:file,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;
const module1={exports:{}};
new Function('require','module','exports',code)(id=>id==='./artifactReferencePicker'?require(path.join(root,'dist/core/artifactReferencePicker.js')):require(id),module1,module1.exports);
const {resolveDeferredFormReferences,activeDeferredFormAttachments,plannedArtifactLineage}=module1.exports;
const from='/repo/.topics/assets/a.png',from2='/repo/.topics/assets/b.png',target='.topics/work/evidence/001-1-test.trace.md';
const ref='[a.png](../../assets/a.png)',ref2='[b.png](../../assets/b.png)';
const pending=[{sourcePath:from,sourceReference:ref,sectionKey:'Evidence Material',fieldKey:'Material'},{sourcePath:from2,sourceReference:ref2,sectionKey:'Evidence Material',fieldKey:'Material'}];
const values={'Evidence Material':[{name:'before',fields:{Material:ref,Description:'First'}},{name:'after',fields:{Material:ref2,Description:'Second'}}]};
const outputs=new Map([[from,'.topics/work/evidence/001-1-a-01.png'],[from2,'.topics/work/evidence/001-1-b-02.png']]);
const projected=resolveDeferredFormReferences(values,pending,'/repo',target,outputs);
assert.equal(projected.active.length,2);assert.equal(projected.values['Evidence Material'][0].fields.Description,'First');assert.equal(projected.values['Evidence Material'][1].fields.Description,'Second');
assert.match(projected.values['Evidence Material'][0].fields.Material,/001-1-a-01.png/);assert.match(projected.values['Evidence Material'][1].fields.Material,/001-1-b-02.png/);
assert.equal(values['Evidence Material'][0].fields.Material,ref,'never mutate live pending form values');
assert.equal(activeDeferredFormAttachments({'Evidence Material':[{fields:{Description:ref,Material:'else'}}]},pending).length,0,'text in unrelated field must never stage a move');
assert.equal(activeDeferredFormAttachments({'Evidence Material':[{fields:{Material:'else'}}]},pending).length,0,'deleted attachment must be ignored');
const simple=resolveDeferredFormReferences({Material:ref},[{sourcePath:from,sourceReference:ref,sectionKey:'Material',fieldKey:'Material'}],'/repo',target,outputs);
assert.match(simple.values.Material,/001-1-a-01.png/);
for(const invalid of ['.topics/bad.trace.md','other/001-a.trace.md','.topics/work/000-bad.trace.md'])assert.throws(()=>plannedArtifactLineage(invalid));
console.log('PASS deferred multiple materials, per-entry description, ordinary single field, modified or removed references, safe numeric lineage');
